server:
  port: 8082
  ssl:
    key-store: classpath:serverkeystore.jks
    key-store-type: JKS
    key-store-password: topsecret
    key-alias: tcserver

okta:
  oauth2:
    issuer: https://dev-56745877.okta.com/oauth2/default
    client-id: 
    client-secret: 
    redirect-uri: /authorization-code/callback
