server:
  port: 8082
  ssl:
    key-store: classpath:serverkeystore.jks
    key-store-type: JKS
    key-store-password: topsecret
    key-alias: tcserver

okta:
  oauth2:
    issuer: https://dev-56745877.okta.com/oauth2/default
    client-id: 0oa4s80yxuvD9JEKm5d6
    client-secret: 6WSkL0_NJh04wdUTEhm2ISRpwYknDSxstIIoTN4Y
    redirect-uri: /authorization-code/callback